### ISSUE TITLE
Switching to ElasticSearch for searching

### ISSUE THREAD

**Issue by reteps** [slatinsky/DiscordChatExporter-frontend#11]
Wanted to let you know that in the coming months, I will be forking this project to use ElasticSearch search, and also search text attachments. If this is something you are interested in integrating into the main branch, please let me know!

**Comment by slatinsky** [comment]
Hello,

thank you for your interest in my project. 

I am planing to migrate the project mongodb or sqlite database api backend, because currently we are sending one large json with everything to the browser. Because browser has limited heap memory to 4 GB, we can't scale with this approach above 4 milion messages per guild. 

My goal with this project is also "one click run" on Windows - to make it easy to use releases for everyone. I am worried that it won't be that easy to run with Elastic search added (Java dependency, not easy to install elastic search).

I really like your idea, but I don't know how we can solve the "easy to use" part. Not everyone uses docker.

**Comment by slatinsky** [comment]
@reteps Since version 2.0.0 the project now fetches data from mongodb database by using (fastapi) api. This version may be easier for you to modify to add elasticsearch.

**Comment by slatinsky** [comment]
Closing the enhancement suggestion for now as not planned. The ElasticSearch setup on Windows is not easy to setup for the end user.
