### ISSUE TITLE
Channel is a forum error?

### ISSUE THREAD

**Issue by chaoscreater** [slatinsky/DiscordChatExporter-frontend#40]
Hi there,

I'm trying to export messages from this particular channel and I'm getting this message:

![image](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/18227319/7e856e42-5ddc-46b8-82ad-1504f2cc2c61)

here's the channel in question when I view it in Discord:

![image](https://github.com/slatinsky/DiscordChatExporter-frontend/assets/18227319/10cbd0aa-c056-4664-90dc-9be5223acb2a)

I tried to look up the guides but couldn't find much on this. Could someone point me in the right direction please?

**Comment by slatinsky** [comment]
This issue is not related to this project. This project is just a viewer for json exports made by [Tyrrrz/DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter). Check their wiki [wiki] (https://github.com/Tyrrrz/DiscordChatExporter/tree/master/.docs) for instructions how to export.

If you want to create exports to view in this viewer, you can also checkout instructions in the main [README.md](https://github.com/slatinsky/DiscordChatExporter-frontend#supported-exports)
