### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by Walmarpole** [slatinsky/DiscordChatExporter-frontend#59]
## Expected Behavior
Frontend should display normally.

## Actual Behavior
Front-end displays incorrectly and is unusable. 

Screenshots below:
#### Windows binary:
![app](https://github.com/user-attachments/assets/0278dc71-8e61-469d-9793-2087641149c7)
![app(1)](https://github.com/user-attachments/assets/5a7beea8-8357-46e6-b453-214ddb50eb85)

#### Edge web browser dcef.slada.sk:
![webslada](https://github.com/user-attachments/assets/6eee5cd4-0af1-4ff8-822d-bfc304a448a2)
![webslada(1)](https://github.com/user-attachments/assets/3db0b420-3c55-41c9-9179-6dc7ba99db6d)

## Steps to reproduce the problem

  1. Open DiscordChatExporter-frontend
  2. Wait for preprocessing to finish and GUI to open
  3. Display issue

### Environment

  - Operating system: Windows 11
  - CPU Architecture: x86_64 (PC) 
  - Flavor: (Tested with both) Windows binary release & Docker

### DiscordChatExporter-frontend

  - [Release](https://github.com/slatinsky/DiscordChatExporter-frontend/releases) version or commit hash: v3.0.0
  - Can the issue be reproduced in the [demo](https://dcef.slada.sk/)?: Yes

### [DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter)

- Version (CLI `--version`): v2.43.3

How did you export the data?
  - Export format (CLI `--format`): Json
  - Downloaded assets (CLI `--media`): Yes
  - Markdown processing (CLI `--markdown`): No

## Logs

Nothing relevant.

**Comment by slatinsky** [comment]
Hello,

the project uses [your system browser](https://pywebview.flowrl.com/guide/web_engine.html#known-issues-and-limitations), so I don't have to ship an entire chromium browser with DCE-Frontend (which adds another 100 MB to the download size). It requires [Edge Runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) to be installed on your system (which should be already preinstalled on fully updated Windows 11). It will display the same content as the Edge browser (in your case), because it is Edge.

I only test DCE-Frontend on Chrome and Firefox, but the latest versions of Edge is based on Chromium, so it's internally the same rendering engine as Chrome.

DCE-Frontend also exposes a webserver on port 21011, so you can open [127.0.0.1:21011](http://127.0.0.1:21011/) in different browser (Firefox / Chrome) as an easy fix.

Sorry, I can't reproduce your issue on latest Windows 10 + Edge, latest Windows 10 + Chrome or latest Windows 10 + Firefox. I also tested it on outdated (~1 year) Windows 10 installation + Edge and it worked fine. Please update your system and try again. Or try a different browser.
